export const LADDER_GEOMETRY = {
  leftRailX: 42,
  rungStartX: 58,
  rightRailX: 980,
  topPadding: 28,
  rungBaseHeight: 92,
  branchGap: 56,
  contactWidth: 28,
  contactHeight: 28,
  coilWidth: 42,
  coilHeight: 30,
  blockWidth: 108,
  blockHeight: 72,
  labelFontSize: 12,
  valueFontSize: 10,
  lineWidth: 1.6,
  railWidth: 3,
  bottomSafeArea: 120,
  toolbarHeight: 72,
};